language: node_js
node_js:
  - "10"
python:
  - 3.4
before_install:
- |
    git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '\.md$' || {
      echo "Only docs were updated, stopping build process."
      exit
    }
    sudo apt-get -y install unzip
    sudo apt-get -y install wget
    sudo apt-get -y install python3-pip python-dev
install:
  - sudo pip3 install requests
jobs:
  include:
  - name: "Check Header"
    env: TEST=check_header
  - name: "Unit Test"
    env: TEST=unit_test
  - name: "Code Scan"
    env: TEST=code_scan
  - name: "Smoke Test"
    env: TEST=smoke_test
script: >
  if [ x${TEST} = xcheck_header ]; then
    git clone --branch=devops https://github.com/kevinchcn/data-annotator-for-machine-learning.git devops
    echo $TRAVIS_BUILD_DIR
    cp $TRAVIS_BUILD_DIR/devops/check_headers.py .
    chmod +x check_headers.py
    python3 ./check_headers.py -f "$(git diff --name-only --diff-filter=d $TRAVIS_COMMIT_RANGE)"
  fi &&
  if [ x${TEST} = xunit_test ]; then
    echo unit test Start
    echo unit test End
  fi &&
  if [ x${TEST} = xcode_scan ]; then
    echo Scan Start
    echo Scan End
  fi &&
  if [ x${TEST} = xsmoke_test ]; then
    git clone --branch=devops https://github.com/kevinchcn/data-annotator-for-machine-learning.git devops
    echo $TRAVIS_BUILD_DIR
    cp -r $TRAVIS_BUILD_DIR/devops/* .
    chmod +x annotation-app/docker-entrypoint.sh
    docker-compose up -d
    docker-compose ps
    docker ps
    echo Smoke Test Start
    cd autotest
    npm install
    npm run webdriver
    npm run e2e
    echo Smoke Test End
  fi
