dist: Xenial
sudo: false
group: deprecated-2017Q4
language: node_js
node_js:
  - "10"
python:
  - 3.4
before_install:
- |
    sudo apt-get -y install unzip
    sudo apt-get -y install wget
    sudo apt-get -y install python3-pip python-dev
install:
  - sudo pip3 install requests
jobs:
  include:
   - name: "Code Scan"
     env: TEST=code_scan
before_script:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi
script: >
  if [ x${TEST} = xcode_scan ]; then
    SONARSCANNER='sonar-scanner-cli-4.0.0.1744-linux'
    SONARSCANNERINNER='sonar-scanner-4.0.0.1744-linux'
    npm install npm
    npm install tslint
    npm install typescript
    tsc -v
    wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/$SONARSCANNER.zip
    unzip $SONARSCANNER.zip
    rm -f $SONARSCANNER.zip
    mkdir -p original-code
    shopt -s extglob
    mv !($SONARSCANNERINNER|original-code) original-code/
    str=$(printf '=%.0s' {1..50})
    echo $str Docker Start $str 
    git clone --branch=devops https://github.com/Kai-Qiao/data-annotator-for-machine-learning.git devops
    cp -r $TRAVIS_BUILD_DIR/devops/* original-code/
    cp -a devops/sonar/* .
    cp -a devops/autotest original-code/
    rm -rf devops
    cd original-code/
    chmod +x annotation-app/docker-entrypoint.sh
    docker-compose up -d
    docker-compose ps
    sleep 5
    echo $str Docker Done $str     
    echo $str Smoke Test Start $str 
    cd annotation-app/
    npm install
    npm run build
    cd ../autotest/
    npm install
    npm run webdriver
    npm run e2e-smoke
    sed -i 's/dist\/root\///g' coverage-output/lcov.info
    cd ../..
    echo $str Smoke Test End $str 
    echo $str Code Scan app Start $str	
    python ./config_sonar_project.py -ProjectName $SONAR_ORG-DAML-$TRAVIS_BRANCH-annotation-app -ProjectKey $SONAR_ORG-DAML-$TRAVIS_BRANCH-annotation-app -OrgKey $SONAR_ORG -QualityGateName angular-client-gate -QualityGateConditions ./quality_gates/angular-client.json -SonarToken $SONAR_TOKEN
    ./$SONARSCANNERINNER/bin/sonar-scanner -Dsonar.typescript.lcov.reportPaths="original-code/autotest/coverage-output/lcov.info" -Dsonar.sources=./original-code/annotation-app/ -Dsonar.exclusions=**/node_modules/**/*,**/models/**/*,**/downloadProject/**/*,**/logs/**/*,**/venv/**/*,**/__pycache__/**/*,*.md,*.txt,*.yml -Dsonar.projectName=$SONAR_ORG-DAML-$TRAVIS_BRANCH-annotation-app -Dsonar.branch.name=master -Dsonar.projectKey=$SONAR_ORG-DAML-$TRAVIS_BRANCH-annotation-app -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=$SONAR_ORG -Dsonar.login=$SONAR_TOKEN -Dsonar.c.file.suffixes=- -Dsonar.cpp.file.suffixes=- -Dsonar.objc.file.suffixes=-
    echo $str Code Scan app End $str
    echo $str Code Scan service Start $str	
    python ./config_sonar_project.py -ProjectName $SONAR_ORG-DAML-$TRAVIS_BRANCH-annotation-service -ProjectKey $SONAR_ORG-DAML-$TRAVIS_BRANCH-annotation-service -OrgKey $SONAR_ORG -QualityGateName angular-client-gate -QualityGateConditions ./quality_gates/angular-client.json -SonarToken $SONAR_TOKEN
    ./$SONARSCANNERINNER/bin/sonar-scanner -Dsonar.sources=./original-code/annotation-service/ -Dsonar.exclusions=**/node_modules/**/*,**/models/**/*,**/downloadProject/**/*,**/logs/**/*,**/venv/**/*,**/__pycache__/**/*,*.md,*.txt,*.yml -Dsonar.projectName=$SONAR_ORG-DAML-$TRAVIS_BRANCH-annotation-service -Dsonar.branch.name=master -Dsonar.projectKey=$SONAR_ORG-DAML-$TRAVIS_BRANCH-annotation-service -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=$SONAR_ORG -Dsonar.login=$SONAR_TOKEN -Dsonar.c.file.suffixes=- -Dsonar.cpp.file.suffixes=- -Dsonar.objc.file.suffixes=-
    echo $str Code Scan service End $str
    echo $str Code Scan al $str	
    python ./config_sonar_project.py -ProjectName $SONAR_ORG-DAML-$TRAVIS_BRANCH-active-learning-service -ProjectKey $SONAR_ORG-DAML-$TRAVIS_BRANCH-active-learning-service -OrgKey $SONAR_ORG -QualityGateName angular-client-gate -QualityGateConditions ./quality_gates/angular-client.json -SonarToken $SONAR_TOKEN
    ./$SONARSCANNERINNER/bin/sonar-scanner -Dsonar.sources=./original-code/active-learning-service/ -Dsonar.exclusions=**/node_modules/**/*,**/models/**/*,**/downloadProject/**/*,**/logs/**/*,**/venv/**/*,**/__pycache__/**/*,*.md,*.txt,*.yml -Dsonar.projectName=$SONAR_ORG-DAML-$TRAVIS_BRANCH-active-learning-service -Dsonar.branch.name=master -Dsonar.projectKey=$SONAR_ORG-DAML-$TRAVIS_BRANCH-active-learning-service -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=$SONAR_ORG -Dsonar.login=$SONAR_TOKEN -Dsonar.c.file.suffixes=- -Dsonar.cpp.file.suffixes=- -Dsonar.objc.file.suffixes=-
    echo $str Code Scan al End $str
    git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '\.travis\.yml$' || {
      echo "No need to check sonar quality gate for only travis configuration updates"
      exit
    }
    sleep 5 && python3 ./check_sonar_qualitygate.py -ProjectKeyPrefixArray=$SONAR_ORG-singleton-angular-client-$TRAVIS_BRANCH -HostName=https://sonarcloud.io
  fi
