/*
Copyright 2019-2023 VMware, Inc.
SPDX-License-Identifier: Apache-2.0
*/

import { Injectable } from '@angular/core';
import '@cds/core/icon/register.js';
import {
  ClarityIcons,
  userIcon,
  unknownIcon,
  talkBubblesIcon,
  happyFaceIcon,
  tagsIcon,
  dataClusterIcon,
  helpIcon,
  infoStandardIcon,
  envelopeIcon,
  flaskIcon,
  boltIcon,
  rackServerIcon,
  successStandardIcon,
  lightbulbIcon,
  textIcon,
  unknownStatusIcon,
  bundleIcon,
  imageIcon,
  errorStandardIcon,
  tableIcon,
  uploadCloudIcon,
  fileIcon,
  windowCloseIcon,
  viewListIcon,
  downloadIcon,
  barsIcon,
  flagIcon,
  childArrowIcon,
  ellipsisVerticalIcon,
  exclamationCircleIcon,
  angleIcon,
  circleIcon,
  banIcon,
  checkIcon,
  noteIcon,
  trashIcon,
  uploadIcon,
  usersIcon,
  pencilIcon,
  plusIcon,
  checkboxListIcon,
  refreshIconName,
  refreshIcon,
  sadFaceIcon,
} from '@cds/core/icon';
import { ClrSpinner } from '@clr/angular';

ClarityIcons.addIcons(
  unknownIcon,
  userIcon,
  talkBubblesIcon,
  happyFaceIcon,
  tagsIcon,
  dataClusterIcon,
  helpIcon,
  infoStandardIcon,
  envelopeIcon,
  flaskIcon,
  boltIcon,
  rackServerIcon,
  successStandardIcon,
  lightbulbIcon,
  textIcon,
  unknownStatusIcon,
  bundleIcon,
  imageIcon,
  errorStandardIcon,
  tableIcon,
  uploadCloudIcon,
  fileIcon,
  windowCloseIcon,
  viewListIcon,
  downloadIcon,
  barsIcon,
  flagIcon,
  childArrowIcon,
  ellipsisVerticalIcon,
  exclamationCircleIcon,
  angleIcon,
  circleIcon,
  successStandardIcon,
  banIcon,
  checkIcon,
  noteIcon,
  trashIcon,
  uploadIcon,
  usersIcon,
  pencilIcon,
  plusIcon,
  checkboxListIcon,
  refreshIcon,
  sadFaceIcon,
);

@Injectable({
  providedIn: 'root',
})
export class CdsIconsService {
  constructor() {}
}
