# Copyright 2019-2021 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

version: '2'
services:
  annotation-app:
    container_name: app
    image: 1107899648/vmware-daml-annotation-app:latest
    depends_on:
      - annotation-service
    ports:
      - "4200:5000"
    networks:
      - bridge
    restart: always
  
  annotation-service:
    container_name: as
    image: 1107899648/vmware-daml-annotation-service:latest
    environment:
      - MONGODB_URL=mongodb://host.docker.internal:27017/daml
      - LOOP_AL_URL=http://als:8000/api
    depends_on:
      - active-learning-service
    ports:
      - "3000:3000"
    networks:
      - bridge
    volumes:
      - "./data/as:/app/FILE_SYS"
    restart: always
   
  active-learning-service:
    container_name: als
    image: 1107899648/vmware-daml-active-learning-service:latest
    environment:
      - MONGODB_URL=mongodb://host.docker.internal:27017/daml
    ports:
       - "8000:8000"
    networks:
       - bridge
    volumes:
      - "./data/als:/app/models"
    restart: always
  
networks:
  bridge:
    driver: bridge