#
# Copyright 2019-2021 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0
#

name: sonarcloud_scan_service

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ['**']

jobs:
  #sonar cloud scan job for annotation service
  scan_annotation_service:
    runs-on: ubuntu-latest 

    #define variables to be used for SonarCloud scan
    env:
      SONAR_ORG: ${{ secrets.SONAR_ORG }}

    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Checkout devops branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'devops'
          path: 'devops'

      - name: SonarCloud setup for annotation-service
        working-directory: ./devops/sonar
        run: python ./config_sonar_project.py -ProjectName ${{ env.SONAR_ORG }}-annotation-service -ProjectKey ${{ env.SONAR_ORG }}-annotation-service -OrgKey ${{ env.SONAR_ORG }} -QualityGateName annotation-service -QualityGateConditions ./quality_gates/angular-client.json -SonarToken ${{ secrets.SONAR_TOKEN }}

      - name: SonarCloud Scan annotation-service
        uses: sonarsource/sonarcloud-github-action@v1.9  
        with:
          projectBaseDir: ./annotation-service
          args: >
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.projectKey=${{ env.SONAR_ORG }}-annotation-service
            -Dsonar.test.exclusions=**/node_modules/**/*,**/FILE_SYS/**/*,**/logs/**/*,*.md,*.txt,*.yml 
            -Dsonar.coverage.exclusions=**
        #Set below secrets in your Github Actions secrets
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.DATA_GITHUB_TOKEN }}

  #sonar cloud scan job for active learning service
  scan_active_learning_service:
    runs-on: ubuntu-latest 

    #define variables to be used for SonarCloud scan
    env:
      SONAR_ORG:  ${{ secrets.SONAR_ORG }}

    steps:  
      - name: Checkout 
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout devops branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'devops'
          path: 'devops'

      - name: SonarCloud setup for active-learning-service
        working-directory: ./devops/sonar
        run: python ./config_sonar_project.py -ProjectName ${{ env.SONAR_ORG }}-active-learning-service -ProjectKey ${{ env.SONAR_ORG }}-active-learning-service -OrgKey ${{ env.SONAR_ORG }} -QualityGateName active-learning -QualityGateConditions ./quality_gates/angular-client.json -SonarToken ${{ secrets.SONAR_TOKEN }}

      - name: SonarCloud Scan active-learning-service
        uses: sonarsource/sonarcloud-github-action@v1.9  
        with:
          projectBaseDir: ./active-learning-service
          args: >
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.projectKey=${{ env.SONAR_ORG }}-active-learning-service
            -Dsonar.test.exclusions=**/models/**/*,**/downloadProject/**/*,**/logs/**/*,**/venv/**/*,**/__pycache__/**/*,*.md,*.txt,*.yml 
            -Dsonar.coverage.exclusions=**
        #Set below secrets in your Github Actions secrets
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.DATA_GITHUB_TOKEN }}

          
